NarwianskiZakatek/Models/Warning.cs
namespace NarwianskiZakatek.Models
{
    public class Warning
    {
        public int WarningId { get; set; }
        public string Message { get; set; } = string.Empty;
        public string UserId { get; set; } = string.Empty;
        public AppUser User { get; set; } = new AppUser();
        public bool WasDisplayed { get; set; } = false;
    }
}

NarwianskiZakatek/Controllers/PostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NarwianskiZakatek.Data;
using NarwianskiZakatek.Models;
using NarwianskiZakatek.Repositories;
using NarwianskiZakatek.Services;
using NarwianskiZakatek.ViewModels;
using System.Data;

namespace NarwianskiZakatek.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostsService _service;
        private readonly IUsersService _userService;

        public PostsController(IPostsService service, IUsersService userService)
        {
            _service = service;
            _userService = userService;
        }

        // GET: Posts
        public async Task<IActionResult> Index(int? pageNumber)
        {
            var username = HttpContext.User.Identity?.Name;
            ViewBag.Warnings = _userService.GetUserWarnings(username);

            int pageSize = 10;
            return View(_service.GetPostsPage(pageNumber ?? 1, pageSize));
        }

        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Admin(string? message, int? pageNumber)
        {
            ViewBag.Message = message;
            int pageSize = 10;
            return View(_service.GetPostsPage(pageNumber ?? 1, pageSize));
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = _service.GetPostDetails((int)id);
            return post == null ? NotFound() : View(post);
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,Employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,DateCreated,Content,File")] PostViewModel post)
        {
            if (ModelState.IsValid)
            {
                await _service.CreatePost(post);
                return RedirectToAction("Admin", new { message = "Post został utworzony." });
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = _service.GetPostDetails((int)id);
            return post == null ? NotFound() : View(new PostViewModel()
            {
                PhotoUrl = post.getFullPhotoPath(),
                PostId = post.PostId,
                Title = post.Title,
                Content = post.Content,
                DateCreated = post.DateCreated
            });
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int id, PostViewModel editedPost)
        {
            if (id != editedPost.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid && await _service.UpdatePost(editedPost))
            {
                return RedirectToAction("Admin", new { message = "Post został zaktualizowany." });
            }
            return View(editedPost);
        }

        // GET: Posts/Delete/5
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = _service.GetPostDetails((int)id);
            return post == null ? NotFound() : View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.Delete(id);
            return RedirectToAction("Admin", new { message = "Post został usunięty." });
        }
    }
}

NarwianskiZakatek/Controllers/ReservationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NarwianskiZakatek.Data;
using NarwianskiZakatek.Models;
using NarwianskiZakatek.Repositories;
using NarwianskiZakatek.Services;
using NarwianskiZakatek.ViewModels;

namespace NarwianskiZakatek.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly IReservationsService _service;
        private readonly IUsersService _userService;

        public ReservationsController(IReservationsService service, IUsersService userService)
        {
            _service = service;
            _userService = userService;
        }

        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Index(int? pageNumber, string? sortOrder, DateTime? beginFrom, DateTime? beginTo, DateTime? endFrom, DateTime? endTo, decimal? priceFrom, decimal? priceTo)
        {
            var username = HttpContext.User.Identity?.Name;
            ViewBag.Warnings = _userService.GetUserWarnings(username);

            ViewBag.BeginFrom = beginFrom;
            ViewBag.BeginTo = beginTo;
            ViewBag.EndFrom = endFrom;
            ViewBag.EndTo = endTo;
            ViewBag.PriceFrom = priceFrom;
            ViewBag.PriceTo = priceTo;
            ViewBag.SortOrder = sortOrder;

            return View(await _service.GetReservationsByParams(10, pageNumber, sortOrder, beginFrom, beginTo, endFrom, endTo, priceFrom, priceTo, null));
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult DetailsFull(string id)
        {
            Reservation reservation = _service.GetReservation(id);
            ViewBag.Rooms = _service.GetRoomsByReservation(reservation);
            return View(reservation);
        }

        [HttpGet]
        [Authorize(Roles = "User,Admin,Employee")]
        public IActionResult Date(string? message)
        {
            ViewBag.Message = message;
            return View();
        }
        [HttpGet]
        [Authorize(Roles = "User,Admin,Employee")]
        public async Task<IActionResult> MyReservations(string? message, int? pageNumber, string? sortOrder, DateTime? beginFrom, DateTime? beginTo, DateTime? endFrom, DateTime? endTo, decimal? priceFrom, decimal? priceTo)
        {
            var user = _userService.GetUserByUsername(HttpContext.User.Identity.Name);
            ViewBag.Message = message;
            ViewBag.SortOrder = sortOrder;
            ViewBag.BeginFrom = beginFrom;
            ViewBag.BeginTo = beginTo;
            ViewBag.EndFrom = endFrom;
            ViewBag.EndTo = endTo;
            ViewBag.PriceFrom = priceFrom;
            ViewBag.PriceTo = priceTo;

            return View(await _service.GetReservationsByParams(10, pageNumber, sortOrder, beginFrom, beginTo, endFrom, endTo, priceFrom, priceTo, user.Id));
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin,Employee")]
        [ValidateAntiForgeryToken]
        public IActionResult New(DateTime beginDate, DateTime endDate)
        {
            if (beginDate <= DateTime.Now)
            {
                return RedirectToAction("Date", new { message = "Nie możesz rezerwować pobytu z datą przeszłą." });
            }
            if (endDate <= beginDate)
            {
                return RedirectToAction("Date", new { message = "Data zakończenia rezerwacji nie może być wcześniejsza, niż data rozpoczęcia." });
            }
            ViewBag.RoomList = _service.FindAvailableRooms(beginDate, endDate);
            return View(new RoomsViewModel()
            {
                BeginDate = beginDate,
                EndDate = endDate
            });
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin,Employee")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmAsync(RoomsViewModel roomList)
        {
            _service.AddReservation(roomList, HttpContext.User.Identity.Name);
            return RedirectToAction("MyReservations", new { message = "Rezerwacja została złożona." });
        }

        [HttpGet]
        [Authorize(Roles = "User,Admin,Employee")]
        public IActionResult Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var reservation = _service.GetReservation(id);
            if (reservation == null)
            {
                return NotFound();
            }
            if (HttpContext.User.Identity.Name != reservation.User.UserName)
            {
                return LocalRedirect("/Identity/Account/AccessDenied");
            }
            return View(reservation);
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin,Employee")]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(string id)
        {
            var reservation = _service.GetReservation(id);
            if (reservation == null)
            {
                return NotFound();
            }
            if (HttpContext.User.Identity.Name != reservation.User.UserName)
            {
                return LocalRedirect("/Identity/Account/AccessDenied");
            }
            _service.CancelReservation(reservation);
            return RedirectToAction("MyReservations", new { message = "Rezerwacja została anulowana." });
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Employee")]
        public IActionResult DeleteAny(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var reservation = _service.GetReservation(id);
            return reservation == null ? NotFound() : View(reservation);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Employee")]
        [ActionName("DeleteAny")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteAnyPost(string id)
        {
            var reservation = _service.GetReservation(id);
            _service.CancelReservation(reservation);
            return RedirectToAction("Index", new { message = "Rezerwacja została anulowana." });
        }

        [Authorize(Roles = "User,Admin,Employee")]
        public IActionResult Rate(string id)
        {
            var reservation = _service.GetReservation(id);
            if (HttpContext.User.Identity.Name != reservation.User.UserName)
            {
                return LocalRedirect("/Identity/Account/AccessDenied");
            }
            return HttpContext.User.Identity.Name != reservation.User.UserName ?
                LocalRedirect("/Identity/Account/AccessDenied") :
                View(new OpinionViewModel()
                {
                    ReservationId = id
                });
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin,Employee")]
        [ValidateAntiForgeryToken]
        public IActionResult Rate(OpinionViewModel opinionViewModel)
        {
            var reservation = _service.GetReservation(opinionViewModel.ReservationId);
            if (HttpContext.User.Identity.Name != reservation.User.UserName)
            {
                return LocalRedirect("/Identity/Account/AccessDenied");
            }
            _service.RateReservation(opinionViewModel, reservation);
            return RedirectToAction("MyReservations", new { message = "Dziękujemy za udzielenie opinii." });
        }

        [Authorize(Roles = "User,Admin,Employee")]
        public IActionResult Details(string id)
        {
            Reservation reservation = _service.GetReservation(id);
            ViewBag.Rooms = _service.GetRoomsByReservation(reservation);
            return HttpContext.User.Identity.Name != reservation.User.UserName ?
                LocalRedirect("/Identity/Account/AccessDenied") : View(reservation);
        }
    }
}

NarwianskiZakatek/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NarwianskiZakatek.Data;
using NarwianskiZakatek.Models;
using NarwianskiZakatek.Repositories;
using NarwianskiZakatek.Services;
using System.Data;

namespace NarwianskiZakatek.Controllers
{
    public class RoomsController : Controller
    {
        private readonly IRoomsService _service;

        public RoomsController(IRoomsService repository)
        {
            _service = repository;
        }

        // GET: Rooms
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Index(string? message)
        {
            ViewBag.Message = message;
            return View(_service.GetRooms());
        }

        // GET: Rooms/Create
        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Create([Bind("RoomNumber,RoomCapacity,Price,IsActive")] Room room)
        {
            if (ModelState.IsValid)
            {
                _service.AddRoom(room);
                return RedirectToAction(nameof(Index));
            }
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            return View(room);
        }

        // GET: Rooms/Edit/5
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var room = await _service.Get((int)id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int id, [Bind("RoomId,RoomNumber,RoomCapacity,Price,IsActive")] Room room)
        {
            if (id != room.RoomId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                string message;
                try
                {
                    message = await _service.UpdateRoom(room);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction("Index", new { message = message });
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var room = await _service.Get((int)id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string message = "Pokój nie został usunięty, gdyż istnieją w systemie powiązane z nim rezerwacje." +
                " Jeżeli chcesz wycofać pokój z użytku, zmień jego dostępność w oknie edycji pokoju.";

            var room = await _service.Get((int)id);
            if (await _service.Delete(room))
            {
                message = "Pomyślnie usunięto pokój o numerze " + room.RoomNumber + ".";
            }
            return RedirectToAction("Index", new { message = message });
        }
    }
}

NarwianskiZakatek/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NarwianskiZakatek</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NarwianskiZakatek.styles.css" asp-append-version="true" />
    <link href="~/css/calendar.css" rel="stylesheet" />
    <link href="~/css/weather.css" rel="stylesheet" />
</head>

<body class="bg-black with-bottom-space">
    <header>
        <div class="container-fluid no-pad">
            <img class="fit" src="~/graphics/Header.jpg" runat="server" />
            <div class="top-right">
                <a class="pagetitle fs-1" asp-controller="Posts" asp-action="Admin">Narwiański Zakątek</a>
            </div>
        </div>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarSupportedContent">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Edit" asp-route-header="Noclegi">Noclegi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Edit" asp-route-header="Restauracja">Restauracja</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Edit" asp-route-header="Atrakcje">Atrakcje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Edit" asp-route-header="Okolica">Okolica</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Reservations" asp-action="Index">Rezerwacje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Edit" asp-route-header="O nas">O nas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Admin" asp-action="Users">Użytkownicy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Rooms" asp-action="Index">Pokoje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Posts" asp-action="Admin">Posty</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-white">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <div class="col-lg-4 col-md-12">
                <div>
                    <partial name="_Calendar" />
                </div>
                <div>
                    <partial name="_Weather" />
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
    @RenderSection("css", required: false)
</body>
<footer class="border-top footer text-muted footer-custom">
    <div class="container black">
        &copy; @DateTime.Now.Year - Narwiański Zakątek, Wydział Informatyki Politechniki Białostockiej
    </div>
</footer>
</html>

NarwianskiZakatek/Views/Shared/_Calendar.cshtml
<div id="calendar_body">
    <div id="calendar_container">
        <div id="calendar_header">
        </div>

        <div id="weekdays">
            <div>Pn</div>
            <div>Wt</div>
            <div>Śr</div>
            <div>Czw</div>
            <div>Pt</div>
            <div>So</div>
            <div>Nd</div>
        </div>

        <div id="calendar"></div>
    </div>
    <script src="~/js/calendar.js"></script>
</div>

NarwianskiZakatek/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NarwianskiZakatek</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NarwianskiZakatek.styles.css" asp-append-version="true" />
    <link href="~/css/weather.css" rel="stylesheet" />
    <link href="~/css/calendar.css" rel="stylesheet" />
    
</head>

<body class="bg-black with-bottom-space">
    <header>
        <div class="container-fluid no-pad">
            <img class="fit" src="~/graphics/header.jpg" runat="server" />
            <div class="top-right">
                <a class="pagetitle fs-1" asp-controller="Posts" asp-action="Index">Narwiański Zakątek</a>
            </div>
        </div>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarSupportedContent">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Accomodation">Noclegi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Catering">Restauracja</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Attractions">Atrakcje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Neighborhood">Okolica</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Reservations" asp-action="MyReservations" title="Manage">Rezerwacje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="About">O nas</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-white">
        <div class="row">
            <div class="col-lg-8">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <div class="col-lg-4">
                <div>
                    <partial name="_Calendar" />
                </div>
                <div>
                    <partial name="_Weather" />
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
    @RenderSection("css", required: false)
</body>
<footer class="border-top footer text-muted footer-custom">
    <div class="container black">
        &copy; @DateTime.Now.Year - Narwiański Zakątek, Wydział Informatyki Politechniki Białostockiej
    </div>
</footer>
</html>

NarwianskiZakatek/Views/Shared/_ReservationFilter.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="form-actions no-color">
    <h3>Filtrowanie</h3>
    <div class="row">
        <div class="col-md-2">
            <p>
                Data rozpoczęcia od:
            </p>
        </div>
        <div class="col-md-4">
            <input class="form-control" type="datetime-local" data-val="true" id="beginFrom" name="beginFrom" value="@ViewBag.BeginFrom">
        </div>
        <div class="col-md-6">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p>
                Data rozpoczęcia do:
            </p>
        </div>
        <div class="col-md-4">
            <input class="form-control" type="datetime-local" data-val="true" id="beginTo" name="beginTo" value="@ViewBag.BeginTo">
        </div>
        <div class="col-md-6">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p>
                Data zakończenia od:
            </p>
        </div>
        <div class="col-md-4">
            <input class="form-control" type="datetime-local" data-val="true" id="endFrom" name="endFrom" value="@ViewBag.EndFrom">
        </div>
        <div class="col-md-6">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p>
                Data zakończenia do:
            </p>
        </div>
        <div class="col-md-4">
            <input class="form-control" type="datetime-local" data-val="true" id="endTo" name="endTo" value="@ViewBag.EndTo">
        </div>
        <div class="col-md-6">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p>
                Cena od:
            </p>
        </div>
        <div class="col-md-4">
            <input class="form-control valid" type="text" id="priceFrom" name="priceFrom" value="@ViewBag.PriceFrom">
        </div>
        <div class="col-md-6">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p>
                Cena do:
            </p>
        </div>
        <div class="col-md-4">
            <input class="form-control valid" type="text" id="priceTo" name="priceTo" value="@ViewBag.PriceTo">
        </div>
        <div class="col-md-6">
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(function () {
            $("#beginDateFrom").datepicker;
            $("#beginDateTo").datepicker;
            $("#endDateFrom").datepicker;
            $("#endDateTo").datepicker;
        });
    </script>
}

NarwianskiZakatek/Views/Shared/_StatusMessage.cshtml
@if(!string.IsNullOrEmpty(ViewBag.Message)){
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @ViewBag.Message
    </div>
}

NarwianskiZakatek/Views/Shared/_Warning.cshtml
@foreach (var message in ViewBag.Warnings)
{
    if (!string.IsNullOrEmpty(message))
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            @message
        </div>
    }
}

NarwianskiZakatek/Views/Shared/_Weather.cshtml
<div id="weather_body">
    <div id="weather_container">
        <div id="current_day">
            <div id="date_today"></div>
            <img id="icon_today"/>
            <div id="temperature_today"></div>
            <div id="description_today"></div>
        </div>

        <div id="forecast"></div>
    </div>
    <script src="~/js/weather.js"></script>
</div>